version: "3.9"
services:
  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
  mongo:
    image: mongo:4.0
    volumes:
      - ./mongo/data:/data/db
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
